### ISSUE TITLE
空指针错误

### ISSUE THREAD

**Issue by arnold117** [dotponder/SleepMinder#1]
在安装完成后提示空指针错误。而在Android 5.0上正常运行。
位于分支 chart-2-4-jar

错误提示
```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.arnold.sleepminder, PID: 5909
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.arnold.sleepminder/com.arnold.sleepminder.activities.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.arnold.sleepminder.lib.Recorder.isRunning()' on a null object reference
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4631)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4842)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:113)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:149)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:103)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2928)
        at android.os.Handler.dispatchMessage(Handler.java:117)
        at android.os.Looper.loopOnce(Looper.java:205)
        at android.os.Looper.loop(Looper.java:293)
        at android.app.ActivityThread.main(ActivityThread.java:9596)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:586)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1204)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.arnold.sleepminder.lib.Recorder.isRunning()' on a null object reference
        at com.arnold.sleepminder.activities.MainActivity.onCreate(MainActivity.java:55)
        at android.app.Activity.performCreate(Activity.java:8488)
        at android.app.Activity.performCreate(Activity.java:8461)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1343)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4602)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4842) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:113) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:149) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:103) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2928) 
        at android.os.Handler.dispatchMessage(Handler.java:117) 
        at android.os.Looper.loopOnce(Looper.java:205) 
        at android.os.Looper.loop(Looper.java:293) 
        at android.app.ActivityThread.main(ActivityThread.java:9596) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:586) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1204) 
```

**Comment by YunTianming675** [comment]
原因：`synchronizeStartButtonState(MyApplication.recorder.isRunning());` 这里，MyApplication类的onCreate方法没在应用启动时自动调用，导致recorder和context是空指针
可能的解决办法：
- 自己添加一个 init 方法，在里面初始化变量
- 将 MyApplication 作为单例实现，想办法为 static 的对象赋值
> 想完美解决有点难搞，因为 static 块里不能用继承的方法 :(
> MainActivity 的 setupNightList 还有 **NullPointerException**
